// QRDrop Phase 1 — Signaling + Bare WebRTC
// Three parallel writer lanes with disjoint file ownership, then integration, then fresh-context review.
// See ORCHESTRATION.md for the model routing policy and the concurrency contract.

const COMMON = [
  "PROJECT: QRDrop - a symmetric, browser-based E2EE P2P file-transfer PWA. Repo root: /mnt/warehouse/source/QRDrop",
  "",
  "READ FIRST, in this order (mandatory):",
  "  1. AGENTS.md - hard rules. TypeScript strict everywhere. NEVER use third-party crypto libs (Web Crypto API only).",
  "     NEVER store session data in IndexedDB, Cache API, or localStorage.",
  "  2. PLAN.md - the specification. Follow it exactly. Your assigned sections are named below.",
  "  3. ORCHESTRATION.md - toolchain gotchas. Critical: TypeScript is v7.0.2, where the 'baseUrl' compiler option",
  "     has been REMOVED. Never reintroduce it. Path aliases must use relative values.",
  "",
  "SCOPE: You are implementing PHASE 1 ONLY (PLAN.md section 16, 'Phase 1 - Signaling + Bare WebRTC').",
  "Do NOT implement later phases. Where a later phase will extend your code, build a clean seam and leave a",
  "short comment naming the phase that will use it - but stop at Phase 1 behaviour.",
  "",
  "HARD BOUNDARIES - violating these breaks two other lanes running concurrently in this same directory:",
  "  - Create or edit ONLY the paths listed under YOUR FILES. Nothing else.",
  "  - NEVER touch: package.json, pnpm-workspace.yaml, tsconfig.json, tsconfig.base.json, vite.config.ts,",
  "    vitest.config.ts, wrangler.toml, index.html, worker-configuration.d.ts, TODO.md, ORCHESTRATION.md,",
  "    PLAN.md, AGENTS.md. These are parent-owned. If you need a new dependency or a config change,",
  "    DO NOT make it - report it as a blocker in your final output.",
  "  - Run NO git commands whatsoever (no add/commit/stash/checkout). The parent owns git.",
  "    Concurrent git access corrupts the shared index.",
  "  - Do NOT run 'pnpm install'. Every dependency is already installed and the lockfile is final.",
  "  - Do NOT edit TODO.md; report blockers in your final output instead.",
  "  - You MAY run 'pnpm --filter <pkg> typecheck' and 'pnpm --filter <pkg> test' to check your own work.",
  "    Expect errors caused by files other lanes have not written yet. Do not fix their files and do not",
  "    delete or stub out your own code just to make a whole-repo typecheck pass.",
  "",
  "QUALITY BAR:",
  "  - TypeScript strict mode is ON, plus noUncheckedIndexedAccess. Write code that satisfies them;",
  "    never use 'any' to escape, never add @ts-ignore or @ts-expect-error.",
  "  - Handle errors explicitly. No unhandled promise rejections. No console.log of sensitive material.",
  "  - Add focused unit tests for pure logic you introduce. Do not write tests that need a real browser,",
  "    real WebRTC, or a real Cloudflare runtime - extract pure functions and test those instead.",
  "",
  "FINAL OUTPUT: a concise report containing (a) files created, (b) how to run what you built,",
  "(c) any contract deviation you made and why, (d) blockers or things the parent must decide.",
  "Do not paste large amounts of source code into the report."
].join("\n");

const CONTRACT = [
  "",
  "=== SHARED CONTRACT (lane B implements this, lanes C and A code against it) ===",
  "These signatures are normative. If you must deviate, keep it a strict superset and say so in your report.",
  "",
  "// apps/frontend/src/lib/signaling.ts",
  "export type SignalingMessage =",
  "  | { type: 'join'; role: 'host' | 'guest'; publicKey: string }",
  "  | { type: 'pubkey'; publicKey: string }",
  "  | { type: 'offer'; sdp: string }",
  "  | { type: 'answer'; sdp: string }",
  "  | { type: 'ice'; candidate: RTCIceCandidateInit }",
  "  | { type: 'paired' }",
  "  | { type: 'error'; message: string }",
  "",
  "export class SignalingClient {",
  "  constructor(url: string)                                  // base URL, e.g. ws://localhost:8787",
  "  connect(sessionCode: string, role: 'host' | 'guest', publicKey: string): Promise<void>",
  "  send(msg: SignalingMessage): void",
  "  onMessage(cb: (msg: SignalingMessage) => void): () => void // returns an unsubscribe function",
  "  onClose(cb: (info: { code: number; reason: string }) => void): () => void",
  "  onError(cb: (err: unknown) => void): () => void",
  "  close(): void",
  "}",
  "NOTE: In Phase 1 there are no keys yet, so callers pass publicKey: '' (empty string).",
  "Phase 2 fills it with a raw/base64 P-256 public key. Keep the field, do not remove it.",
  "",
  "// apps/frontend/src/lib/webrtc.ts",
  "export type HelloMessage = { t: 'hello'; from: 'host' | 'guest'; text: string }",
  "export type PeerConnectionOptions = { turnUsername?: string; turnCredential?: string }",
  "",
  "export class PeerConnection {",
  "  constructor(opts?: PeerConnectionOptions)",
  "  initAsHost(): Promise<RTCSessionDescriptionInit>",
  "  receiveAnswer(answer: RTCSessionDescriptionInit): Promise<void>",
  "  receiveOffer(offer: RTCSessionDescriptionInit): Promise<RTCSessionDescriptionInit>",
  "  addIceCandidate(c: RTCIceCandidateInit): Promise<void>",
  "  onIceCandidate(cb: (c: RTCIceCandidateInit) => void): () => void",
  "  onDataChannelOpen(cb: () => void): () => void",
  "  onMessage(cb: (msg: HelloMessage) => void): () => void",
  "  onStateChange(cb: (s: RTCPeerConnectionState) => void): () => void",
  "  send(msg: HelloMessage): void",
  "  close(): void",
  "}",
  "",
  "// HTTP route contract served by the worker (lane A) and consumed by the UI (lane C)",
  "GET /session/new  -> 200 JSON: code (string), turnCredentials (object with username, credential)",
  "GET /session/:code/ws -> WebSocket upgrade (101). Invalid code format -> 400. Unknown/expired -> 404.",
  "GET /healthz -> 200 plain text 'ok'",
  "=== END SHARED CONTRACT ==="
].join("\n");

const LANE_A = [
  COMMON,
  "",
  "YOU ARE: Lane A - Cloudflare Worker + Durable Object signaling server.",
  "PLAN.md sections to implement: 13 (Signaling Server: routes, DO state machine, SignalingMessage,",
  "rate limiting, TURN credentials), 18 (Environment Variables), and the signaling-relevant rows of 17",
  "(Security Checklist) and 2 (Threat Model).",
  "",
  "YOUR FILES (create only these, under apps/signaling-worker/):",
  "  src/index.ts            - fetch handler, routing, CORS, rate limiting, WS upgrade",
  "  src/session.ts          - SessionDurableObject (the Durable Object class)",
  "  src/turn.ts             - generateTurnCredentials",
  "  src/codes.ts            - session code generation + strict validation",
  "  src/types.ts            - shared SignalingMessage + internal types (exported)",
  "  src/codes.test.ts, src/turn.test.ts, src/session.test.ts - vitest unit tests",
  "  src/env-extra.d.ts      - ONLY if you must augment the generated Env (e.g. TURN_SECRET, ALLOWED_ORIGINS).",
  "                            Note: a .d.ts sharing a basename with a .ts file is silently dropped by TS - that",
  "                            is why this file is named env-extra.d.ts. Do not rename it.",
  "",
  "REQUIREMENTS:",
  "1. codes.ts - generateSessionCode() returns 8 characters drawn from the unambiguous alphabet",
  "   '23456789ABCDEFGHJKMNPQRSTVWXYZ' (32 chars; excludes 0,1,I,L,O,U so a human can transcribe a fallback",
  "   code by hand). Use crypto.getRandomValues - never Math.random. Export isValidSessionCode(code)",
  "   implementing strict server-side validation (exactly length 8, every char in that alphabet).",
  "   PLAN.md section 17 requires codes be validated server-side BEFORE any DO lookup - enforce that ordering",
  "   in index.ts so malformed input can never reach a Durable Object.",
  "2. turn.ts - generateTurnCredentials(secret, ttlSeconds) per PLAN.md section 13:",
  "   username = (unixSecondsNow + ttlSeconds) + ':' + randomId; credential = base64(HMAC-SHA256(secret, username)).",
  "   Use Web Crypto (crypto.subtle) only - no libraries. It will be async; that is fine.",
  "   If TURN_SECRET is unset, return null and let index.ts omit turnCredentials rather than throwing.",
  "3. session.ts - export class SessionDurableObject implementing the state machine",
  "   CREATED -> HOST_CONNECTED -> GUEST_CONNECTED -> EXCHANGING -> DONE, exactly per PLAN.md section 13.",
  "   It holds EXACTLY two WebSockets (one host, one guest). It brokers join/pubkey/offer/answer/ice only.",
  "   On reaching the paired state it sends a 'paired' message to both sockets, then destroys all stored state",
  "   and self-destructs (clear storage, close sockets). Per PLAN.md section 19 decision 6 it stores nothing else.",
  "   Session codes expire 300s after creation (SESSION_TTL_SECONDS) - refuse joins after expiry.",
  "   A second host or a third participant must be rejected. Log NOTHING sensitive: no SDP, no ICE,",
  "   no public keys, no message payloads (PLAN.md section 17).",
  "   IMPORTANT: wrangler resolves the DO class from the main module, so index.ts must re-export it:",
  "   export the SessionDurableObject binding from './session'.",
  "   Extract the pure state-transition logic into a separately exported function so session.test.ts can",
  "   test it without a Durable Object runtime.",
  "4. index.ts - routing exactly per the HTTP contract above. Create/retrieve the DO with",
  "   env.SESSION.idFromName(code). Pass the code and role into the DO (a query string on the WS URL is fine).",
  "   CORS: allow origins listed in env.ALLOWED_ORIGINS (comma-separated), defaulting to http://localhost:5173",
  "   so the Vite dev server can call /session/new cross-origin. Handle OPTIONS preflight. Reflect the request",
  "   Origin only when it is on the allowlist.",
  "   Rate limiting per PLAN.md section 13: max 10 join attempts per IP per minute via the env.RATE_LIMIT KV",
  "   binding, keyed on CF-Connecting-IP. CRITICAL: that KV binding may be undefined locally (its id in",
  "   wrangler.toml is a placeholder and there are no Cloudflare credentials on this machine), so treat it as",
  "   OPTIONAL - when absent, skip limiting and continue. Never crash because KV is missing.",
  "5. Env typing: worker-configuration.d.ts is ALREADY GENERATED and parent-owned. It declares Env with",
  "   SESSION_TTL_SECONDS, TURN_TTL_SECONDS, RATE_LIMIT and the SESSION DO binding. Read it to confirm the",
  "   exact shape before coding. Anything missing (TURN_SECRET, ALLOWED_ORIGINS) goes in src/env-extra.d.ts",
  "   via interface augmentation - do not edit the generated file.",
  "6. This is a Workers runtime: no DOM, no Node builtins (nodejs_compat was deliberately removed).",
  "   Use only Web APIs.",
  "",
  "TESTS: cover code format/alphabet/uniqueness and validation rejection of bad input; TURN credential",
  "username format, HMAC verifiability and expiry arithmetic; and the pure DO state-transition function",
  "(including rejecting a second host and expiring a stale session). Tests run in a plain node environment.",
  CONTRACT,
  "",
  "VERIFY before finishing: run 'pnpm --filter @qrdrop/signaling-worker typecheck' and",
  "'pnpm --filter @qrdrop/signaling-worker test'. Both must pass for YOUR files.",
  "Also confirm the worker bundles: 'pnpm --filter @qrdrop/signaling-worker build'.",
  "Do NOT run 'wrangler deploy' - there are no Cloudflare credentials."
].join("\n");

const LANE_B = [
  COMMON,
  "",
  "YOU ARE: Lane B - frontend transport libraries (signaling client + WebRTC peer connection).",
  "PLAN.md sections to implement: 12 (WebRTC Module: ICE configuration, connection lifecycle, PeerConnection",
  "class API) and the SignalingMessage half of 13. Also read 10 (Wire Protocol) and 11 (Crypto) for CONTEXT",
  "ONLY - encryption itself is Phase 2, do not implement it.",
  "",
  "YOUR FILES (create only these, under apps/frontend/):",
  "  src/lib/signaling.ts",
  "  src/lib/webrtc.ts",
  "  src/lib/signaling.test.ts",
  "  src/lib/webrtc.test.ts",
  "",
  "REQUIREMENTS:",
  "1. signaling.ts - implement SignalingClient exactly per the shared contract below. It opens a WebSocket to",
  "   <base>/session/<code>/ws, sends a join message with role and publicKey on open, and dispatches inbound",
  "   messages to subscribers. Every on* method returns an unsubscribe function (React needs clean teardown).",
  "   PLAN.md section 19 decision 10: NO reconnect logic - sessions are single-use. Surface close/error as",
  "   events; never leave an unhandled rejection or throw from inside an event callback.",
  "   connect() must reject if the socket fails to open or closes before the join is accepted.",
  "   Parse inbound frames defensively: malformed JSON becomes an onError, not a crash.",
  "2. webrtc.ts - implement PeerConnection with EXACTLY the API in the contract. Key points:",
  "   - ICE servers per PLAN.md section 12: stun:stun.cloudflare.com:3478 plus the turn/turns entries.",
  "     The TURN username/credential arrive from the worker, so accept them via PeerConnectionOptions and",
  "     build the RTCIceServer list from them. When they are absent, configure STUN only rather than sending",
  "     empty credentials. iceTransportPolicy must be 'all' (PLAN.md section 17: try direct first, TURN fallback).",
  "     Add a comment noting TODO.md flags the turns port question for Phase 7.",
  "   - Host creates the DataChannel; guest receives it via ondatachannel. Label it 'qrdrop-main', ordered and",
  "     reliable for Phase 1. Comment that Phase 3 file chunking may want a separate unreliable/unordered channel.",
  "   - PHASE 2 SEAM (important): route every outbound frame through one private encode method and every",
  "     inbound frame through one private decode method, so Phase 2 can insert AES-256-GCM in exactly two",
  "     places without touching any call site. In Phase 1 these are a JSON string round-trip. Document the",
  "     seam with a comment naming Phase 2 and the PLAN.md section 10 envelope (12-byte IV then ciphertext+tag).",
  "   - Phase 1 payload type is HelloMessage. Keep send/onMessage generic enough that Phase 3 can widen the",
  "     payload to protocol.ts WireMessage without rewriting call sites.",
  "   - Buffer ICE candidates that arrive before the remote description is set, and flush them afterwards - this",
  "     is the single most common WebRTC handshake bug and signaling races will hit it.",
  "   - Expose connection state via onStateChange so the UI can render Connecting/Connected/Ended/Error.",
  "   - close() must be idempotent, remove all listeners, and never throw.",
  "3. No third-party libraries, and NO crypto of any kind in this phase (Web Crypto arrives in Phase 2).",
  "4. Do not create anything under src/lib/ that is not listed above. In particular do NOT create",
  "   protocol.ts, crypto.ts, safetyPhrase.ts, chunker.ts or library.ts - those belong to later phases.",
  "",
  "TESTS: a real RTCPeerConnection does not exist in node or jsdom, so extract and test the pure parts:",
  "ICE server list construction with and without TURN credentials, the encode/decode round-trip through the",
  "Phase 2 seam, and candidate-buffering/flush logic. For signaling, inject a fake WebSocket and test URL",
  "construction, the join frame, dispatch, unsubscribe, and malformed-frame handling. Design the classes so",
  "this injection is possible (e.g. an optional socket factory) without weakening the public API.",
  CONTRACT,
  "",
  "VERIFY before finishing: 'pnpm --filter @qrdrop/frontend test' must pass for your test files.",
  "Typecheck will fail on files belonging to Lane C that do not exist yet - that is expected; make sure",
  "errors are not attributable to YOUR files."
].join("\n");

const LANE_C = [
  COMMON,
  "",
  "YOU ARE: Lane C - React app shell, routing, stores, hooks and the Phase 1 screens.",
  "PLAN.md sections to implement: 7 (Home Screen layout), 8 (Session Flow - Phase 1 only needs the",
  "'Connecting' status and a minimal active state), 9 (Session Data Model - the SessionState shape),",
  "and 5 (Repository Structure - match its file layout). Skim 15 (PWA) for the #0f0f0f theme colours only.",
  "",
  "YOUR FILES (create only these, under apps/frontend/):",
  "  src/main.tsx",
  "  src/config.ts",
  "  src/vite-env.d.ts",
  "  src/styles.css",
  "  src/store/sessionStore.ts",
  "  src/hooks/useWebRTC.ts",
  "  src/hooks/useSession.ts",
  "  src/pages/Home.tsx",
  "  src/pages/Session.tsx",
  "  src/pages/Settings.tsx",
  "  src/components/QRDisplay.tsx",
  "  src/components/library/LibraryBrowser.tsx",
  "  .env.example",
  "",
  "REQUIREMENTS:",
  "1. main.tsx - React 19 createRoot, BrowserRouter with routes '/' -> Home, '/session' -> Session,",
  "   '/settings' -> Settings. Import styles.css.",
  "2. config.ts - read import.meta.env.VITE_SIGNALING_URL and VITE_APP_URL with safe local-dev defaults",
  "   (ws://localhost:8787 and http://localhost:5173). Type them properly via ImportMetaEnv in vite-env.d.ts.",
  "   .env.example documents both, and comments that 'wrangler dev' serves the worker on port 8787.",
  "3. store/sessionStore.ts - zustand store holding SessionState EXACTLY as specified in PLAN.md section 9",
  "   (role, phase, sessionCode, safetyPhrase, phraseConfirmed, items, connectionState) plus actions.",
  "   Phase 1 only exercises idle/connecting/active/ended; declare the safetyPhrase, phraseConfirmed and",
  "   items fields now so Phase 2 and Phase 3 can fill them without a store rewrite.",
  "4. pages/Home.tsx - follow the ASCII layout in PLAN.md section 7: header with the QRDrop title and a link",
  "   to Settings; the QR panel; the caption 'Scan this to send files here'; a 'Your Library' section; and a",
  "   'Scan & Send' button. PHASE 1 EXPLICITLY USES A STATIC QR PLACEHOLDER showing a hardcoded session URL as",
  "   text inside a bordered box - real QR rendering is Phase 6 and camera scanning is Phase 6 too. Render the",
  "   'Scan & Send' button disabled with a note that scanning arrives in Phase 6. Do NOT touch a camera API.",
  "5. components/QRDisplay.tsx - a presentational placeholder that takes a url string and renders it in the",
  "   bordered box described above, structured so Phase 6 can swap in a canvas from the 'qrcode' package",
  "   without changing its props. Leave that as a comment.",
  "6. components/library/LibraryBrowser.tsx - STUB ONLY: an empty state saying the library arrives in",
  "   Phase 5. Absolutely no IndexedDB access in Phase 1 (that is Phase 5, and AGENTS.md forbids session data",
  "   in IDB regardless).",
  "7. pages/Session.tsx - the Phase 1 integration target, per PLAN.md section 8 role rules:",
  "   read the 'code' URL param; present -> role 'guest'; absent -> role 'host'. A host with no code calls",
  "   GET <signaling>/session/new, then displays the returned code as text and uses it. Then: host creates the",
  "   offer, guest answers, ICE candidates relay through signaling, and once the DataChannel is open BOTH sides",
  "   send a HelloMessage and render the peer's text on screen. Show the status bar states from PLAN.md",
  "   section 8 Phase 1: Connecting / Connected / Ended / Error. On unmount and on beforeunload, close cleanly.",
  "8. hooks/useWebRTC.ts and useSession.ts - keep all signaling/WebRTC orchestration here so Session.tsx stays",
  "   readable. This is the seam Phase 2 extends with ECDH key exchange; comment it as such. Subscribe and",
  "   unsubscribe correctly (every on* call in the contract returns an unsubscribe function) and guard against",
  "   React 19 StrictMode double-invocation opening two peer connections.",
  "9. pages/Settings.tsx - minimal placeholder noting export/import arrives in Phase 7, with a link home.",
  "10. styles.css - dark theme, page background #0f0f0f to match PLAN.md section 15, mobile-first, legible",
  "    type scale, no CSS framework (none is installed). Keep it compact.",
  "",
  "CRITICAL DEPENDENCY NOTE: you import from '../lib/signaling' and '../lib/webrtc', which Lane B is writing",
  "RIGHT NOW in parallel. Code against the exact contract below and DO NOT create those files yourself, even",
  "if typecheck says they are missing. Missing-module errors for those two paths are EXPECTED and will be",
  "resolved by the integration lane. Do not stub them, do not inline copies.",
  "",
  "Also do NOT import or create anything for tiptap, msgpack, idb, qrcode or html5-qrcode - all later phases.",
  CONTRACT,
  "",
  "VERIFY before finishing: run 'pnpm --filter @qrdrop/frontend typecheck'. Ignore ONLY errors of the form",
  "\"Cannot find module '../lib/signaling'\" or '../lib/webrtc'. Every other error is yours to fix."
].join("\n");

// ---- Model routing with automatic failover ---------------------------------
// AGENTS.md rule 1 says use omnirouter/agy gemini; rule 2 says fall back to
// agentrouter/deepseek-v4-flash when agy runs out. As of 2026-09-12 the gemini
// route is hard-EXCLUDED for ~18h (Connection error, expires 20:56Z), so deepseek
// leads. Final entry `null` means "omit model" -> inherit the parent session model
// (qwen3.8-max), which is verified working and can never be quota-excluded.
// This guarantees no lane can dead-end on a provider outage overnight.
const MODEL_CHAIN = [
  "agentrouter/deepseek-v4-flash",
  "omnirouter/agy/gemini-3.8-flash-high",
  null
];

// Plain (non-async) helper returning a promise chain, per pi-subagents portability
// rules. Each retry uses a distinct workflow key so resume/identity stays unambiguous.
function runOpts(key, opts, idx) {
  const i = idx === undefined ? 0 : idx;
  const model = MODEL_CHAIN[i];
  const o = Object.assign({}, opts);
  if (model) { o.model = model; } else { delete o.model; }
  const suffix = i === 0 ? "" : "-fb" + i;
  return runs.run(key + suffix, o).then(function (r) {
    if (r && r.ok) { return r; }
    if (i + 1 >= MODEL_CHAIN.length) { return r; }
    emit("lane " + key + " failed on " + String(model) + "; retrying on " + String(MODEL_CHAIN[i + 1] || "inherited session model"));
    return runOpts(key, opts, i + 1);
  });
}

const ACC = { level: "checked", evidence: ["changed-files", "commands-run", "validation-output", "residual-risks"] };

const lanes = await Promise.all([
  runOpts("p1-lane-a-worker", { label: "Build signaling worker + Durable Object", agent: "worker", task: LANE_A, acceptance: ACC }),
  runOpts("p1-lane-b-transport", { label: "Build signaling client + WebRTC peer", agent: "worker", task: LANE_B, acceptance: ACC }),
  runOpts("p1-lane-c-ui", { label: "Build React shell + Home/Session pages", agent: "worker", task: LANE_C, acceptance: ACC })
]);

const names = ["Lane A (signaling worker)", "Lane B (transport libs)", "Lane C (UI shell)"];
emit("Phase 1 lanes settled: " + lanes.map((r, i) => names[i] + "=" + (r.ok ? "ok" : "FAILED")).join(", "));

const laneSummary = lanes.map((r, i) => {
  return names[i] + " -> ok=" + String(r.ok) + "\n" + String(r.output ?? r.error ?? "").slice(0, 3000);
}).join("\n\n----------------------------------------\n\n");

const integration = await runOpts("p1-integrate", {
  label: "Integrate Phase 1 lanes to green build",
  agent: "worker",
  task: [
    "YOU ARE: the Phase 1 integration lane for QRDrop (repo root /mnt/warehouse/source/QRDrop).",
    "Three parallel lanes just wrote disjoint parts of Phase 1. Your job is to make the WHOLE repo",
    "typecheck, test and build together, fixing every seam mismatch between them.",
    "",
    "Read AGENTS.md, ORCHESTRATION.md (toolchain gotchas - note TypeScript is v7.0.2 and 'baseUrl' is",
    "removed), and PLAN.md sections 12, 13, 7, 8, 9 and the Phase 1 checklist in 16.",
    "",
    "DO THIS:",
    "  1. Run: pnpm -r typecheck   then: pnpm -r test   then: pnpm -r build",
    "  2. Fix every error until all three commands pass cleanly across both workspace packages.",
    "  3. Where two lanes disagree about a signature, make the code match the SHARED CONTRACT below.",
    "     Prefer fixing the consumer unless the producer clearly violates the contract.",
    "  4. Confirm Phase 1 functional intent is actually wired end to end: Session.tsx reads the ?code param,",
    "     host/guest roles are assigned per PLAN.md section 8, the offer/answer/ICE relay goes through",
    "     SignalingClient, PeerConnection opens the 'qrdrop-main' DataChannel, and both sides exchange a",
    "     HelloMessage that reaches the screen. Repair wiring that is missing or dead.",
    "  5. Sanity-check the worker entry: index.ts must re-export SessionDurableObject so wrangler can find it.",
    "",
    "STRICT PROHIBITIONS - fixing a build by weakening the project is a FAILED outcome:",
    "  - Do not relax tsconfig strictness, and do not remove noUncheckedIndexedAccess or verbatimModuleSyntax.",
    "  - Do not add @ts-ignore, @ts-expect-error, eslint-disable, or 'any' casts to silence errors.",
    "  - Do not delete, skip (.skip/.todo), or hollow out tests to get a green run. Fix the code instead.",
    "  - Do not add new dependencies or run 'pnpm install'.",
    "  - Do not run any git command. The parent owns git.",
    "  - Do not edit PLAN.md, AGENTS.md, ORCHESTRATION.md or TODO.md.",
    "  - If a fix genuinely requires a config or dependency change, STOP and report it as a blocker for the",
    "    parent instead of making it.",
    "",
    "FINAL OUTPUT: the exact final status of all three commands, a list of every seam mismatch you fixed",
    "(file, what disagreed, what you chose), any remaining known issue, and any blocker needing a parent",
    "decision. Do not paste large source listings.",
    CONTRACT
  ].join("\n"),
  acceptance: {
    level: "checked",
    evidence: ["changed-files", "commands-run", "validation-output", "residual-risks"],
    verify: [{ id: "typecheck", command: "pnpm -r typecheck", timeoutMs: 300000 }]
  }
});

emit("Integration done, launching review");

const review = await runOpts("p1-review", {
  label: "Fresh-context review of Phase 1",
  agent: "reviewer",
  task: [
    "Fresh-context review of QRDrop Phase 1 (repo root /mnt/warehouse/source/QRDrop). You have no prior context;",
    "read the code yourself. You are READ-ONLY: do not edit any file.",
    "",
    "Read AGENTS.md, PLAN.md (especially sections 2 Threat Model, 7 Home, 8 Session Flow, 12 WebRTC,",
    "13 Signaling Server, 16 Phase 1 checklist, 17 Security Checklist, 19 Key Design Decisions) and",
    "ORCHESTRATION.md. Then review the Phase 1 implementation in apps/signaling-worker/src and",
    "apps/frontend/src.",
    "",
    "Judge these specific seams, in priority order:",
    "  P0 SECURITY/PRIVACY:",
    "   - Does the Durable Object log or persist anything sensitive (SDP, ICE, public keys, payloads)?",
    "     PLAN.md section 17 requires it logs nothing and destroys state after 'paired'.",
    "   - Is any session data written to IndexedDB, Cache API or localStorage? AGENTS.md forbids it absolutely.",
    "   - Any third-party crypto library? Only Web Crypto is permitted (none should exist yet in Phase 1).",
    "   - Is the session code validated server-side BEFORE the DO lookup? Can a malformed code reach a DO?",
    "   - Does the rate limiter fail open safely when the KV binding is absent, without crashing the worker?",
    "  P0 CORRECTNESS:",
    "   - DO state machine: can a second host join? Can a third socket attach? Is the 300s expiry enforced?",
    "     Is state actually destroyed on 'paired', and are both sockets closed?",
    "   - WebRTC handshake: are ICE candidates that arrive before the remote description is set buffered and",
    "     flushed? (This is the classic failure and the signaling race will hit it.)",
    "   - Are all event subscriptions unsubscribed on teardown? Any leak or double-connect under React 19",
    "     StrictMode? Is close() idempotent?",
    "  P1 ARCHITECTURE / FUTURE PHASES:",
    "   - Is the Phase 2 encryption seam real - i.e. does ALL traffic pass through exactly one encode and one",
    "     decode point in webrtc.ts, so AES-256-GCM can be inserted without touching call sites?",
    "   - Does SessionState in the store match PLAN.md section 9 exactly, so Phase 2/3 need no rewrite?",
    "   - Do SignalingClient and PeerConnection match the shared contract, including unsubscribe returns?",
    "  P1 SCOPE DISCIPLINE:",
    "   - Was anything from Phase 2-8 implemented early (crypto, tiptap, msgpack, IDB, real QR, camera)?",
    "     Early implementation is a finding, not a bonus.",
    "   - Are there stubs that silently do nothing where Phase 1 required real behaviour?",
    "",
    "Label each concrete finding P0 / P1 / P2 with file and line evidence. Distinguish real defects from",
    "stylistic preference; do not pad. Say explicitly when something is correct and you verified it.",
    "End with exactly one line: 'Merge verdict: BLOCK' or 'Merge verdict: OK' or 'Merge verdict: OK with notes'."
  ].join("\n")
});

return {
  lanes: lanes.map((r, i) => ({ lane: names[i], ok: r.ok ?? null })),
  laneReports: laneSummary,
  integrationOk: integration.ok ?? null,
  integrationReport: String(integration.output ?? integration.error ?? "").slice(0, 6000),
  reviewVerdict: String(review.output ?? review.error ?? "").slice(0, 9000)
};
